#!/bin/sh
# check if os is virtualized on vmware
if [ "$(dmidecode -s system-product-name)" != "VMware Virtual Platform" ]; then exit 0; fi

# create runtime directory
if [ ! -d "/run/vmblock-fuse" ]
then
  mkdir -p "/run/vmblock-fuse"
  chmod 755 "/run/vmblock-fuse"
fi

# start the service
/usr/bin/vmware-vmblock-fuse -d -f -o subtype=vmware-vmblock,default_permissions,allow_other /run/vmblock-fuse
